name: nmr-biology-tools
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - biopython
  - mrcfile
  - openmm
  - mdtraj
  - mdanalysis
  - pdbfixer
  - parmed
  - rdkit
  - openbabel
  - ambertools
  - openff-toolkit
  - openff-forcefields
  - openff-interchange
  - openmmforcefields
  - alchemlyb
  - pymbar
  - pdb2pqr
